import "@repo/ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@repo/ui/lib/utils";
import { DotBackground } from "@repo/ui/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "bg-slate-100 relative min-h-screen")}
      >
        <DotBackground />
        <div className="">{children}</div>
      </body>
    </html>
  );
}
